window.ELNORA_CONFIG={
 SUPABASE_URL:"https://SEU-PROJETO.supabase.co",
 SUPABASE_PUBLISHABLE_KEY:"SUA_CHAVE_PUBLICA",
 SITE_URL:"https://SEU-USUARIO.github.io/SEU-REPOSITORIO",
 GA4_MEASUREMENT_ID:"G-XXXXXXXXXX"
};